[profile.default]
src = 'contracts/src'
out = 'contracts/out'
libs = ['contracts/lib']
cache_path = 'foundrys/cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
